import 'dart:async';
import 'dart:convert';

import 'package:flutter/services.dart';

import '../models/domain_model.dart';

/// Local inference timeout for the SLM stage
/// (multimodal-proposals-v1 §7.2 `INFERENCE_TIMEOUT`: 10 s on-device).
/// The ADR-0005 latency budget (SLM < 3.8 s on reference hardware) sits
/// well below this bound; the timeout only guards a hung native engine.
const Duration kSlmTimeout = Duration(seconds: 10);

/// Maximum tokens the SLM may emit for one interpretation. The agreed
/// scenario needs ~110 tokens of structured JSON; 512 leaves headroom for
/// the intent summary without allowing runaway generation (ADR-0005).
const int kSlmMaxTokens = 512;

/// MethodChannel shared with the Android local-SLM bridge
/// (`LocalSlmMethodHandler`, package `com.example.mobile_flutter`). The
/// bridge generates text with llama.cpp (`libllama_jni.so`); everything
/// runs on-device, so the agreed interpretation scenario works in
/// airplane mode.
const MethodChannel kLocalSlmChannel = MethodChannel('case_mobile/local_slm');

/// Diagnostic codes emitted by the local interpretation stage.
///
/// Codes defined by the multimodal-proposals-v1 §7 catalog are reused
/// verbatim; the `SLM_*` constants extend the §7.2 family for
/// engine-level conditions the catalog does not enumerate (native library
/// not linked, weights absent).
abstract final class LocalInterpretationErrorCodes {
  static const String inferenceTimeout = 'INFERENCE_TIMEOUT';
  static const String intentUnrecognized = 'INTENT_UNRECOGNIZED';
  static const String noCommandsGenerated = 'NO_COMMANDS_GENERATED';
  static const String proposedCommandSyntaxError =
      'PROPOSED_COMMAND_SYNTAX_ERROR';
  static const String slmUnavailable = 'SLM_UNAVAILABLE';
}

/// Failure of the on-device interpretation stage. [code] is a §7 catalog
/// code or an `SLM_*` extension; it is copied verbatim into the proposal
/// diagnostics so interpretation errors remain auditable.
class InterpretationException implements Exception {
  const InterpretationException(this.code, this.message, [this.details]);

  final String code;
  final String message;
  final Object? details;

  @override
  String toString() => '[$code] $message';
}

/// A single modelling command inferred by the SLM.
///
/// The SLM emits only the `type` and `payload` of a model-commands-v1
/// command plus its own confidence scores; the `commandId`, `modelId` and
/// `modelVersion` of the envelope are stamped deterministically by the
/// proposal adapter (multimodal-proposals-v1 S2) — the model never gets
/// write authority over identity or concurrency fields.
class InterpretedCommand {
  const InterpretedCommand({
    required this.type,
    required this.payload,
    this.score = 0.5,
    this.fieldScores = const {},
  });

  /// Command type of model-commands-v1 (e.g. `CreateClass`).
  final String type;

  /// Command payload as emitted by the SLM. Validated by the
  /// deterministic dry-run downstream; never trusted blindly.
  final Map<String, dynamic> payload;

  /// SLM confidence for this command, clamped to `[0.0, 1.0]`.
  final double score;

  /// Per-field confidence as reported by the SLM (§3.1.2 `fieldScores`).
  final Map<String, double> fieldScores;
}

/// Structured output of one SLM interpretation over a transcript.
class InterpretationResult {
  const InterpretationResult({
    required this.intentSummary,
    required this.commands,
    this.elapsedMs,
    this.generatedTokens,
    this.rawOutput,
  });

  /// Natural-language summary of the detected intent (§3 `intent.summary`).
  final String intentSummary;

  /// Ordered inferred commands (topologically sorted by the model).
  final List<InterpretedCommand> commands;

  /// Wall-clock time of the native generation, when reported by the
  /// bridge. Recorded as auditable evidence of the resource budget.
  final int? elapsedMs;

  /// Tokens generated by the SLM, when reported by the bridge.
  final int? generatedTokens;

  /// Raw engine output, kept for the `inference_rationale` evidence hash.
  final String? rawOutput;

  /// Parses the raw text emitted by llama.cpp into an
  /// [InterpretationResult]. The engine is grammar-guided, but the output
  /// is still treated as untrusted: the first JSON object spanning the
  /// outermost braces is extracted and every field is validated.
  ///
  /// Throws [InterpretationException] with
  /// `PROPOSED_COMMAND_SYNTAX_ERROR` when no well-formed JSON object or
  /// `commands` array can be recovered.
  static InterpretationResult parse(String rawOutput) {
    final trimmed = rawOutput.trim();
    final start = trimmed.indexOf('{');
    final end = trimmed.lastIndexOf('}');
    if (start < 0 || end <= start) {
      throw const InterpretationException(
        LocalInterpretationErrorCodes.proposedCommandSyntaxError,
        'La salida del SLM no contiene un objeto JSON interpretable.',
      );
    }
    final Object? decoded;
    try {
      decoded = jsonDecode(trimmed.substring(start, end + 1));
    } on FormatException {
      throw const InterpretationException(
        LocalInterpretationErrorCodes.proposedCommandSyntaxError,
        'La salida del SLM no es JSON válido.',
      );
    }
    if (decoded is! Map<String, dynamic>) {
      throw const InterpretationException(
        LocalInterpretationErrorCodes.proposedCommandSyntaxError,
        'La salida del SLM no es un objeto JSON.',
      );
    }

    final summary = decoded['intentSummary'];
    final rawCommands = decoded['commands'];
    if (rawCommands is! List) {
      throw const InterpretationException(
        LocalInterpretationErrorCodes.proposedCommandSyntaxError,
        "La salida del SLM carece del arreglo 'commands'.",
      );
    }

    final commands = <InterpretedCommand>[];
    for (final entry in rawCommands) {
      if (entry is! Map ||
          entry['type'] is! String ||
          entry['payload'] is! Map) {
        throw const InterpretationException(
          LocalInterpretationErrorCodes.proposedCommandSyntaxError,
          'Un comando inferido por el SLM no tiene la forma '
          '{type, payload} exigida por model-commands-v1.',
        );
      }
      commands.add(InterpretedCommand(
        type: entry['type'] as String,
        payload: Map<String, dynamic>.from(entry['payload'] as Map),
        score: _clampScore(entry['score']),
        fieldScores: _fieldScores(entry['fieldScores']),
      ));
    }

    return InterpretationResult(
      intentSummary:
          summary is String && summary.trim().isNotEmpty
              ? summary.trim()
              : 'Intención interpretada por el SLM local.',
      commands: commands,
      rawOutput: rawOutput,
    );
  }

  static double _clampScore(Object? value) {
    final score = value is num ? value.toDouble() : 0.5;
    return score.clamp(0.0, 1.0).toDouble();
  }

  static Map<String, double> _fieldScores(Object? value) {
    if (value is! Map) return const {};
    return {
      for (final e in value.entries)
        if (e.key is String && e.value is num)
          e.key as String: (e.value as num).toDouble().clamp(0.0, 1.0),
    };
  }
}

/// Input handed to the on-device interpreter: the ASR transcript (or a
/// typed prompt) plus the current canonical model snapshot. The snapshot
/// lets the SLM reference existing classes by id for `AddAttribute` and
/// `CreateAssociation` instead of hallucinating identifiers.
class InterpretationRequest {
  const InterpretationRequest({required this.transcript, required this.model});

  final String transcript;
  final DomainModel model;
}

/// On-device interpretation engine (ADR-0005, Opción A — SLM stage).
/// Implementations must never perform network access and must never
/// mutate the canonical model: their only output is a structured
/// [InterpretationResult] that the deterministic gate validates.
abstract class LocalInterpreter {
  /// Whether the on-device engine is ready (native library loaded and
  /// model weights present in app-private storage).
  Future<bool> isAvailable();

  /// Interprets [request] locally and returns the structured commands.
  ///
  /// Throws [InterpretationException] on any engine failure; the code is
  /// always a catalog-compatible diagnostic.
  Future<InterpretationResult> interpret(InterpretationRequest request);
}

/// Builds the grammar-oriented prompt fed to Qwen2.5-1.5B-Instruct
/// (ADR-0005 §"Generación determinista de propuestas"). Pure Dart so it
/// is exercisable in tests and identical across platforms.
abstract final class SlmPromptBuilder {
  /// System+user prompt in the Qwen2.5 chat template. The system block
  /// pins the allowed command vocabulary, the domain types and the
  /// current model snapshot; the user block carries the transcript.
  static String build(InterpretationRequest request) {
    final model = request.model;
    final snapshot = jsonEncode({
      'modelId': model.id,
      'version': model.version,
      'classes': [
        for (final c in model.classes)
          {
            'id': c.id,
            'name': c.name,
            'attributes': [for (final a in c.attributes) a.name],
          },
      ],
    });

    final buffer = StringBuffer()
      ..writeln('<|im_start|>system')
      ..writeln(
          'Eres el extractor de intenciones UML de la app CASE. Interpreta '
          'la transcripción y responde ÚNICAMENTE con un objeto JSON con '
          'esta forma exacta:')
      ..writeln('{"intentSummary": "<resumen breve en español>", '
          '"commands": [{"type": "<tipo>", "payload": {...}, '
          '"score": <0.0-1.0>, "fieldScores": {"<campo>": <0.0-1.0>}}]}')
      ..writeln('Tipos de comando permitidos (model-commands-v1): '
          'CreateClass, AddAttribute, CreateAssociation.')
      ..writeln(
          'Tipos de atributo permitidos: ${DomainModel.allowedTypes.join(', ')}.')
      ..writeln('Multiplicidades permitidas: '
          '${DomainModel.allowedMultiplicities.join(', ')}.')
      ..writeln('Navegabilidad permitida: '
          '${DomainModel.allowedNavigabilities.join(', ')}.')
      ..writeln('Reglas: usa ids tipo slug únicos (cls-*, attr-*, assoc-*); '
          'referencia clases existentes por su id; si no hay intención de '
          'modelado devuelve "commands": []. No escribas nada fuera del JSON.')
      ..writeln('Modelo canónico actual: $snapshot')
      ..writeln('<|im_end|>')
      ..writeln('<|im_start|>user')
      ..writeln(request.transcript)
      ..writeln('<|im_end|>')
      ..writeln('<|im_start|>assistant');
    return buffer.toString();
  }
}

/// llama.cpp interpreter bridged to Android through [kLocalSlmChannel].
///
/// The Dart side owns the prompt and the output parsing; the native side
/// only generates text for a given prompt. When the library or the
/// weights are missing the bridge reports `SLM_UNAVAILABLE` so the
/// pipeline can degrade to the deterministic adapter.
class LlamaChannelInterpreter implements LocalInterpreter {
  const LlamaChannelInterpreter();

  @override
  Future<bool> isAvailable() async {
    try {
      return await kLocalSlmChannel.invokeMethod<bool>('isAvailable') ??
          false;
    } on MissingPluginException {
      return false;
    } on PlatformException {
      return false;
    }
  }

  @override
  Future<InterpretationResult> interpret(
      InterpretationRequest request) async {
    if (request.transcript.trim().isEmpty) {
      throw const InterpretationException(
        LocalInterpretationErrorCodes.intentUnrecognized,
        'No hay texto que interpretar.',
      );
    }

    final prompt = SlmPromptBuilder.build(request);
    final Map<dynamic, dynamic>? raw;
    try {
      raw = await kLocalSlmChannel
          .invokeMethod<Map<dynamic, dynamic>>('generate', {
        'prompt': prompt,
        'maxTokens': kSlmMaxTokens,
      }).timeout(kSlmTimeout);
    } on TimeoutException {
      throw const InterpretationException(
        LocalInterpretationErrorCodes.inferenceTimeout,
        'El modelo de lenguaje local no respondió dentro del límite de 10 s.',
      );
    } on MissingPluginException {
      throw const InterpretationException(
        LocalInterpretationErrorCodes.slmUnavailable,
        'El motor nativo de interpretación no está integrado en esta '
            'compilación.',
      );
    } on PlatformException catch (e) {
      throw InterpretationException(
        _mapPlatformCode(e.code),
        e.message ?? 'Error del intérprete local.',
        e.details,
      );
    }

    final text = (raw?['text'] as String? ?? '').trim();
    if (text.isEmpty) {
      throw const InterpretationException(
        LocalInterpretationErrorCodes.noCommandsGenerated,
        'El modelo local no produjo salida para la transcripción.',
      );
    }
    final result = InterpretationResult.parse(text);
    return InterpretationResult(
      intentSummary: result.intentSummary,
      commands: result.commands,
      elapsedMs: (raw?['elapsedMs'] as num?)?.toInt(),
      generatedTokens: (raw?['generatedTokens'] as num?)?.toInt(),
      rawOutput: result.rawOutput,
    );
  }

  static String _mapPlatformCode(String code) => switch (code) {
        'INFERENCE_TIMEOUT' =>
          LocalInterpretationErrorCodes.inferenceTimeout,
        'INTENT_UNRECOGNIZED' =>
          LocalInterpretationErrorCodes.intentUnrecognized,
        'NO_COMMANDS_GENERATED' =>
          LocalInterpretationErrorCodes.noCommandsGenerated,
        'PROPOSED_COMMAND_SYNTAX_ERROR' =>
          LocalInterpretationErrorCodes.proposedCommandSyntaxError,
        _ => LocalInterpretationErrorCodes.slmUnavailable,
      };
}
